import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import './InnerPages.css';

const Img = ({src, alt, className=''}) => <img className={className} src={src} alt={alt} loading="lazy" />;
const Arrow = ({to,children,light=false}) => <Link className={`ip-arrow ${light?'light':''}`} to={to}>{children}<span>→</span></Link>;
const useReveal = () => useEffect(()=>{const n=document.querySelectorAll('.ip-reveal');const o=new IntersectionObserver(e=>e.forEach(x=>x.isIntersecting&&x.target.classList.add('shown')),{threshold:.1});n.forEach(x=>o.observe(x));return()=>o.disconnect()},[]);

export default function About(){useReveal();return <main className="inner-page about-page">
  <section className="about-hero"><div className="ip-shell about-hero-grid"><div><p className="ip-kicker">About Sweftfly Inc.</p><h1>Technology Hiring,<br/><em>Built Around People.</em></h1><p>Sweftfly Inc. helps organizations across the United States connect with skilled technology professionals through focused recruiting, flexible staffing solutions, and a hiring experience built around real business needs.</p><div className="ip-actions"><Link className="ip-btn" to="/services">Explore Our Services</Link><Link className="ip-btn ghost" to="/contact">Talk to Our Team</Link></div></div><div className="about-hero-image"><Img src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=85" alt="Technology professionals collaborating in a bright modern office"/><aside><b>Technology Talent</b><span>Contract · C2H · Direct Hire</span></aside></div></div></section>
  <section className="ip-section ip-reveal"><div className="ip-shell editorial-split"><h2>More Than Filling Roles.<br/>We Help Build Teams.</h2><div className="long-copy"><p>Sweftfly Inc. is a technology-focused staffing and recruiting company connecting businesses with professionals who can contribute to their teams, projects, and long-term technology goals.</p><p>We believe effective recruiting starts with understanding more than a job description. Our approach considers the technologies involved, the responsibilities of the role, the team environment, the engagement model, and the objectives behind every hire.</p><p>From individual specialists to scalable technology teams, we help organizations navigate hiring with greater clarity and flexibility.</p><Arrow to="/services">How We Work</Arrow></div></div></section>
  <section className="ip-section purpose ip-reveal"><div className="ip-shell"><p className="ip-kicker">Our purpose</p><h2>What Guides Sweftfly</h2><div className="purpose-panels">{[['Our Mission','Make technology hiring simpler and more effective by connecting businesses with professionals whose skills and experience align with the work that needs to be done.'],['Our Approach','Understand the requirement first, identify relevant talent second, and keep communication clear throughout the hiring journey.'],['Our Focus','Build lasting relationships with businesses and technology professionals by providing a recruiting experience based on relevance, responsiveness, and trust.']].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><div><small>{x[0]}</small><p>{x[1]}</p></div></article>)}</div></div></section>
  <section className="ip-section image-story ip-reveal"><div className="ip-shell story-grid"><div className="story-images"><Img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=85" alt="Engineering team exchanging ideas around a project board"/><Img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=85" alt="Recruiter having a natural professional conversation with a candidate"/></div><div><p className="ip-kicker">A people-first approach</p><h2>Good Recruiting Starts<br/>with Understanding.</h2><p>Every hiring requirement has context.</p><p>A growing engineering team may need speed and flexibility. A critical project may require specialized expertise. A permanent role may require deeper alignment between technical experience and team dynamics.</p><p>Sweftfly begins by understanding that context before identifying candidates.</p><p>This helps us focus on relevance instead of simply increasing the number of resumes presented.</p></div></div></section>
  <section className="ip-section difference ip-reveal"><div className="ip-shell"><p className="ip-kicker cyan">Why Sweftfly</p><h2>Designed for Modern<br/>Technology Hiring.</h2><div className="difference-rows">{[['Technology-Focused Recruiting','We concentrate on technology roles and skill sets, helping conversations begin with a stronger understanding of the requirement.'],['Curated Talent','Our goal is to present relevant professionals based on experience, technical alignment, and role requirements rather than overwhelming hiring teams with resumes.'],['Flexible Staffing Models','Support changing workforce needs through contract, contract-to-hire, direct hire, dedicated recruiting, and project-based staffing.'],['Human Communication','Technology can support recruiting, but strong relationships still matter. We keep employers and professionals informed throughout the hiring process.']].map((x,i)=><div key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></div></section>
  <section className="ip-section match-section ip-reveal"><div className="ip-shell"><div className="ip-center"><p className="ip-kicker">Matching with context</p><h2>The Right Match Goes<br/>Beyond a Resume.</h2></div><div className="match-map"><div className="match-core">Right-fit<br/>talent</div>{['Technical Skills','Experience','Role Requirements','Team Alignment','Engagement Model'].map((x,i)=><span key={x} style={{'--i':i}}>{x}</span>)}</div><p className="match-note">We look at the complete hiring requirement so businesses can spend more time speaking with relevant professionals and less time filtering through mismatched applications.</p></div></section>
  <section className="ip-section partner ip-reveal"><div className="ip-shell"><p className="ip-kicker">How we partner</p><h2>Clear. Focused. Collaborative.</h2><div className="partner-line">{[['Listen','Understand your hiring goals, technology environment, responsibilities, timeline, and engagement needs.'],['Align','Define the candidate profile and establish what matters most for the role.'],['Search','Identify technology professionals whose experience aligns with the requirement.'],['Connect','Present selected candidates and coordinate the interview process.'],['Support','Stay involved through selection, onboarding, and the engagement lifecycle.']].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
  <section className="dual-cta ip-reveal"><div><p className="ip-kicker cyan">For businesses</p><h2>A Recruiting Partner<br/>That Understands Technology.</h2><p>Build flexible, capable technology teams without turning recruiting into another full-time project.</p><Arrow to="/hire" light>Hire Talent</Arrow></div><div><p className="ip-kicker">For technology professionals</p><h2>Build the Next Chapter<br/>of Your Career.</h2><p>Connect with opportunities that align with your skills, experience, and professional goals.</p><Arrow to="/careers">Submit Resume</Arrow></div></section>
  <section className="ip-final ip-reveal"><div className="ip-shell"><p className="ip-kicker cyan">Let's connect</p><h2>Behind Every Great<br/>Technology Team Are<br/>Great People.</h2><p>Whether you're building a team or looking for your next opportunity, Sweftfly Inc. is ready to start the conversation.</p><div className="ip-actions"><Link className="ip-btn" to="/hire">Hire Talent</Link><Link className="ip-btn ghost" to="/contact">Contact Us</Link></div></div></section>
</main>}
