import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import './InnerPages.css';

const categories=[
 ['Software Engineering','Professionals experienced in designing, developing, integrating, and maintaining modern enterprise applications and backend systems.',['Java','Spring','Spring Boot','.NET','C#','Python','Node.js','Go','REST APIs','GraphQL','Microservices','Distributed Systems'],['Backend Developer','Java Developer','.NET Developer','Python Developer','Software Engineer','API Developer','Microservices Engineer']],
 ['Frontend & Mobile','Talent building responsive interfaces and mobile experiences across modern product ecosystems.',['React','Angular','Vue.js','Next.js','TypeScript','JavaScript','HTML','CSS','React Native','Flutter','Android','iOS'],['Frontend Engineer','React Developer','Angular Developer','Full Stack Engineer','Mobile Developer','UI Engineer']],
 ['Cloud & DevOps','Cloud and platform professionals who help teams ship, scale, automate, and operate with confidence.',['AWS','Microsoft Azure','Google Cloud','Docker','Kubernetes','Terraform','Jenkins','GitHub Actions','CI/CD','Ansible','Linux','Infrastructure as Code'],['Cloud Engineer','DevOps Engineer','Site Reliability Engineer','Platform Engineer','Cloud Architect','Kubernetes Engineer']],
 ['Data Engineering','Specialists who design reliable pipelines, platforms, and analytical data foundations.',['Python','SQL','Apache Spark','Snowflake','Databricks','Kafka','Airflow','ETL','Data Warehousing','AWS Data Services','Azure Data Factory'],['Data Engineer','ETL Developer','Snowflake Engineer','Databricks Engineer','Data Architect','Analytics Engineer']],
 ['AI & Machine Learning','Professionals turning data and models into responsible, production-ready intelligent systems.',['Python','Machine Learning','Deep Learning','Generative AI','LLMs','NLP','Computer Vision','MLOps','TensorFlow','PyTorch','Data Science'],['Machine Learning Engineer','AI Engineer','Data Scientist','MLOps Engineer','NLP Engineer','Generative AI Engineer']],
 ['Cybersecurity','Security talent supporting resilient applications, infrastructure, identity, and operations.',['Cloud Security','Application Security','IAM','SIEM','SOC','Security Operations','Vulnerability Management','Network Security','DevSecOps','Governance & Compliance'],['Security Engineer','Cybersecurity Analyst','Cloud Security Engineer','SOC Analyst','IAM Engineer','Security Architect']],
 ['Quality Engineering','Quality specialists who build confidence into software through automation and thoughtful test strategy.',['Selenium','Cypress','Playwright','Appium','API Testing','Automation Testing','Performance Testing','Java','Python','CI/CD Testing'],['QA Engineer','SDET','Automation Engineer','Performance Engineer','Test Lead','QA Architect']],
 ['Enterprise Platforms','Platform specialists connecting business operations with adaptable enterprise systems.',['Salesforce','SAP','ServiceNow','Oracle','Microsoft Dynamics 365','Workday'],['Salesforce Developer','Salesforce Administrator','SAP Consultant','ServiceNow Developer','Oracle Specialist','ERP Consultant']],
 ['Infrastructure & Networking','Professionals supporting the systems and networks that keep organizations connected and productive.',['Windows Server','Linux','VMware','Networking','Cisco','Active Directory','Microsoft 365','Azure Infrastructure','Storage','Monitoring'],['Systems Engineer','Network Engineer','Infrastructure Engineer','Cloud Administrator','Network Architect']],
 ['Product & Delivery','Product and delivery leaders who translate business goals into coordinated technology outcomes.',['Business Analysis','Product Management','Scrum','Agile','Project Management','Program Management','Technical Writing','Solution Architecture'],['Business Analyst','Product Manager','Scrum Master','Project Manager','Program Manager','Solution Architect']]
];
const teams=[['Cloud Modernization',['Cloud Architect','DevOps Engineer','Backend Engineer','SRE','Security Engineer'],['AWS','Kubernetes','Terraform','Java','DevSecOps']],['Modern Data Platform',['Data Architect','Data Engineer','Analytics Engineer','BI Developer'],['Snowflake','Databricks','Python','Spark','Power BI']],['Digital Product Team',['Full Stack Engineer','Frontend Engineer','QA Automation','DevOps Engineer','Business Analyst'],['React','Node.js','TypeScript','AWS','Playwright']],['AI Enablement Team',['AI Engineer','ML Engineer','Data Engineer','MLOps Engineer'],['Python','LLMs','PyTorch','Vector Databases','Cloud AI']]];
const Arrow=({to,children,light=false})=><Link className={`ip-arrow ${light?'light':''}`} to={to}>{children}<span>→</span></Link>;

export default function Technologies(){const[selected,setSelected]=useState(0);useEffect(()=>{const n=document.querySelectorAll('.ip-reveal');const o=new IntersectionObserver(e=>e.forEach(x=>x.isIntersecting&&x.target.classList.add('shown')),{threshold:.1});n.forEach(x=>o.observe(x));return()=>o.disconnect()},[]);const c=categories[selected];return <main className="inner-page tech-page">
 <section className="tech-hero"><div className="ip-shell tech-hero-grid"><div><p className="ip-kicker cyan">Technology talent</p><h1>Expertise Across the<br/>Technologies Building<br/><em>What's Next.</em></h1><p>Connect with professionals across software engineering, cloud infrastructure, data, AI, cybersecurity, enterprise platforms, quality engineering, and other critical technology disciplines.</p><div className="ip-actions"><a className="ip-btn" href="#directory">Find Technology Talent</a><Link className="ip-btn ghost" to="/contact">Talk to a Recruiter</Link></div></div><div className="tech-visual"><img src="https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1400&q=85" alt="Technology professionals collaborating around laptops"/><div className="node-core">Sweftfly<br/><b>Talent</b></div>{['Java','React','.NET','Python','AWS','Azure','Kubernetes','Snowflake','Salesforce','AI/ML'].map((x,i)=><span key={x} style={{'--i':i}}>{x}</span>)}</div></div></section>
 <section id="directory" className="ip-section directory ip-reveal"><div className="ip-shell"><div className="directory-head"><p className="ip-kicker">Our talent expertise</p><h2>Technology Talent,<br/>Organized Around Your Needs.</h2><p>Explore the technology disciplines and skill sets Sweftfly can recruit for.</p></div><div className="tech-matrix"><nav>{categories.map((x,i)=><button className={selected===i?'active':''} onClick={()=>setSelected(i)} key={x[0]}><span>{String(i+1).padStart(2,'0')}</span>{x[0]}</button>)}</nav><article key={c[0]}><p className="ip-kicker">Selected discipline</p><h3>{c[0]}</h3><p>{c[1]}</p><small>Core technologies</small><div className="tag-set">{c[2].map(x=><span key={x}>{x}</span>)}</div><small>Typical talent</small><div className="role-list">{c[3].map(x=><span key={x}>{x}</span>)}</div></article></div></div></section>
 <section className="ip-section tech-story ip-reveal"><div className="ip-shell tech-story-grid"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85" alt="Engineers planning a technology solution together"/><div><p className="ip-kicker">From skills to solutions</p><h2>Technology Expertise<br/>That Fits the Work.</h2><p>Different technology initiatives demand different combinations of skills.</p><p>Whether your organization is modernizing applications, moving workloads to the cloud, strengthening data infrastructure, expanding automation, or building AI capabilities, Sweftfly helps identify professionals whose experience aligns with the work ahead.</p></div></div></section>
 <section className="ip-section ecosystem ip-reveal"><div className="ip-shell"><p className="ip-kicker cyan">Connected expertise</p><h2>One Talent Network.<br/>Multiple Technology Domains.</h2><div className="ecosystem-map"><div>Sweftfly<br/><b>Technology Talent</b></div>{['Software','Cloud','DevOps','Data','AI','Security','QA','Enterprise','Infrastructure','Product'].map((x,i)=><button key={x} style={{'--i':i}}>{x}</button>)}</div></div></section>
 <section className="ip-section talent-paths ip-reveal"><div className="ip-shell"><p className="ip-kicker">Project-ready combinations</p><h2>Build the Combination<br/>Your Project Needs.</h2><div className="team-compositions">{teams.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><div className="team-roles">{x[1].map(y=><b key={y}>{y}</b>)}</div><div className="team-tech">{x[2].map(y=><small key={y}>{y}</small>)}</div></article>)}</div></div></section>
 <section className="ip-section tech-match ip-reveal"><div className="ip-shell"><p className="ip-kicker">Technology-first recruiting</p><h2>Skills Matter.<br/>Context Matters More.</h2><div className="tech-stages">{[['Understand the Stack','Identify technologies, architecture, responsibilities, environment, and required experience.'],['Map the Requirement','Translate the role into specific technical capabilities and hiring priorities.'],['Identify Relevant Talent','Search for professionals whose experience aligns with the actual work involved.'],['Connect & Interview','Present selected professionals so your team can focus on meaningful technical conversations.']].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
 <section className="cinematic ip-reveal"><img src="https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1800&q=85" alt="Modern engineering team collaborating across a digital workspace"/><div>Technology changes.<br/><b>The need for great people doesn't.</b></div></section>
 <section className="ip-section employer-ask ip-reveal"><div className="ip-shell"><div><p className="ip-kicker">Specialized talent</p><h2>Can't Find the Skill Set<br/>You're Looking For?</h2></div><div><p>Technology hiring needs don't always fit neatly into a category. Tell us about your stack, project, or role and our recruiting team can help identify the expertise you need.</p><div className="ip-actions"><Link className="ip-btn dark" to="/hire">Tell Us What You Need</Link><Link className="ip-btn line" to="/contact">Contact Recruiting</Link></div></div></div></section>
 <section className="candidate-strip ip-reveal"><div className="ip-shell"><div><p className="ip-kicker cyan">Technology professionals</p><h2>Your Skills Could Be<br/>Exactly What a Team Needs.</h2></div><p>Share your experience with Sweftfly and explore technology opportunities aligned with your expertise.</p><Arrow to="/careers" light>Submit Resume</Arrow></div></section>
</main>}
